### ISSUE TITLE
support browser back button natively

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-client#111]
- when user navigates within the iFrame component (Client Display) notify the parent which will update the URL 
- when back button is clicked OR page is refreshed read relevant portion of the url and notify child component (Client Display)

there will be a need for a corresponding skills-service ticket

Note: After this is complete we should add another ticket to optionally remove back button from the SkillsDisplay component

**Comment by rmmayo** [comment]
corresponding skills-service ticket: NationalSecurityAgency/skills-service#598

**Comment by rmmayo** [comment]
PR: #114

**Comment by sudo-may** [comment]
:+1:
