### ISSUE TITLE
SkillsDisplay: Back button/history entries are lost on reload for Firefox and some versions of chrome

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-client#127]
After refreshing a skills-display component on FireFox and some versions of Chrome (>=90 it seems), the back button no longer works properly.  ie, the page does not change but the url does, or the previous entry appears to be removed and we jump back more than one page.

**Comment by rmmayo** [comment]
PR: #128

**Comment by sudo-may** [comment]
:+1:
