### ISSUE TITLE
SkillsReporter does not retry errors when `configure` is not called first

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-client#144]
the `maxRetryAttempts` is properly initialized in the `configure()` method to either the passed in value, or the the `defaultMaxRetryAttempts`, but if the `configure()` method is not called the default value is not used to initialize and `maxRetryAttempts` will be `undefined` causing any retry attempts to be skipped.

**Comment by rmmayo** [comment]
PR: #145

**Comment by sudo-may** [comment]
:+1:
