### ISSUE TITLE
Is the vue-client compatible with vue 3?

### ISSUE THREAD

**Issue by a-schulz** [NationalSecurityAgency/skills-client#217]
I wanted to use the @skilltree/skills-client-vue:^3.5.0 in my new project with vue 3 but it is not working?
Getting the following error:
`
Uncaught TypeError: this._self is undefined
cu SkillsDisplay.vue:3
`

Don't know if it is compatible with vue 3.

Thanks in advance!

**Comment by sudo-may** [comment]
Hi @a-schulz, thank you for reaching out. Unfortunately right now skills-client library only naively supports Vue 2 but we do now have [a ticket ](https://github.com/NationalSecurityAgency/skills-client/issues/218) to add support for Vue 3. In the meantime you can utilize skills-client JS library in a Vue 3 project: 
https://skilltreeplatform.dev/skills-client/js.html

Hope this helps!
