### ISSUE TITLE
Please include src in the skills-client-vue npm package

### ISSUE THREAD

**Issue by ventralnet** [NationalSecurityAgency/skills-client#26]
**Is your feature request related to a problem? Please describe.**
Including src with your npm package could help with potential debugging.

**Describe the solution you'd like**
include src in the files section of your package.json file, or remove the files section altogether

**Comment by sudo-may** [comment]
@ventralnet thank you for reporting!

**Comment by sudo-may** [comment]
@ventralnet fix was merged to the master, will be released in [@skilltree/skills-client-vue](https://www.npmjs.com/package/@skilltree/skills-client-vue) version 3.0.0; thanks again for reporting!
