### ISSUE TITLE
Investigate adding Snyk support

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-client#27]
Previous attempts at integrating Snyk resulted in the CI build running out of javascript heap in node (https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory). Look into adding Snyk support back in after increasing node heap for CI builds. The Current CI containers have 7GB of total ram available.

**Comment by evenstensberg** [comment]
Why not just the plugin from GitHub?

**Comment by sudo-may** [comment]
@evenstensberg we wanted to evaluate Snyk to see if it would provide additional features/coverage that are currently not offered by GitHub

**Comment by evenstensberg** [comment]
CC @lirantal
