### ISSUE TITLE
Improve error message if skills-sevice host is not trusted by the browser

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-client#28]
client display is loaded via ``https://{skills-service hots}/static/clientPortal/index.html``, if the skills-service host is using self signed cert that url will not be trusted by the browser. The error message displayed to the user is:
```
"Could NOT reach Skills Service"
```

Investigate if there an opportunity to improve that error and clearly indicate what the issue is.

**Comment by rmmayo** [comment]
also print better message to console when trust error occurs for ajax calls

![image](https://user-images.githubusercontent.com/47030042/92115469-77584a00-edc0-11ea-8340-70abaab05dab.png)

**Comment by rmmayo** [comment]
it doesn't look like there is any info available when loading the client display that will allow us to know what is happening other than there is a "Network Error".  Below is the info available:

```
error: {
  "message": "Network Error",
  "name": "Error",
  "stack": "Error: Network Error\n    at Pn (http://localhost:8092/app/assets/js/@skilltree/skills-client-js/dist/skills-client-js.umd.min.js:14:3595)\n    at XMLHttpRequest.Mn.i.onerror (http://localhost:8092/app/assets/js/@skilltree/skills-client-js/dist/skills-client-js.umd.min.js:14:6194)",
  "config": {
    "url": "https://skillspkiclusterlb-64ac32d496273e5e.elb.us-east-1.amazonaws.com/public/status",
    "method": "get",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```

**Comment by mosefer** [comment]
Looks good!
