### ISSUE TITLE
Add angular support to the skills-client library

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-client#5]
Add support for skills-level and skills-display.  Also add a skills-int-client angular app.

**Comment by mosefer** [comment]
@rmmayo skills-client-integration for angular doesn't correctly apply the theme change or summary view for the angular skills display.

**Comment by rmmayo** [comment]
@cjmoses - routing was jacked up.  give it a try now please.

**Comment by mosefer** [comment]
Looks good! Closing.
