### ISSUE TITLE
Consider using webpack

### ISSUE THREAD

**Issue by evenstensberg** [NationalSecurityAgency/skills-client#88]
Hey! I was curious of why you don't use webpack?

**Comment by rmmayo** [comment]
Hi Evan,

Thank you for the question and suggestion!

For the skills-client libs, we started with the framework specific CLI where applicable and then from there tried to standardize on a bundler and went with rollup.  I believe we went with rollup after viewing this [webpack](https://github.com/webpack/webpack/issues/2933#issuecomment-374525241) issue which linked to this [article](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c).

We do utilize webpack in our SkillTree [dashboard ](https://github.com/NationalSecurityAgency/skills-service/tree/master/dashboard) application and it works quite well for us.

**Comment by evenstensberg** [comment]
No worries, thx for explaining!
