### ISSUE TITLE
Allow SkillsConfiguration.configure to be called multiple times

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-client#91]
right now ``SkillsConfiguration.configure`` must only be called once; sometimes clients mistakenly call it on every page load - we should allow that and only perform logic once

**Comment by rmmayo** [comment]
PR: #106

**Comment by sudo-may** [comment]
@rmmayo after further discussion, to stay backwards compatible, we decided to set ``intialized=false`` but still call ``afterConfigure`` without failure
